//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IBMSMSPro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainer
    {
        public int TrainerID { get; set; }
        public string TrainerName { get; set; }
        public string TrainerNarration { get; set; }
    }
}
